name: Generate Timelapse — Last 7 Days (Release, Evenly Spaced)

on:
  workflow_dispatch:
    inputs:
      step_mins:
        description: "Grid spacing in minutes (e.g., 5)"
        required: false
        default: "5"
      tolerance_seconds:
        description: "Max deviation from grid time in seconds (default = step/2)"
        required: false
        default: ""
      fps:
        description: "Frames per second"
        required: false
        default: "24"

permissions:
  contents: write

concurrency:
  group: generate-timelapse-last7
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure output dir
        run: mkdir -p timelapses

      - name: Generate last 7 days timelapse (evenly spaced)
        id: gen
        run: |
          STEP="${{ github.event.inputs.step_mins }}"
          TOL="${{ github.event.inputs.tolerance_seconds }}"
          FPS_IN="${{ github.event.inputs.fps }}"
          [[ -z "$STEP" ]] && STEP=5
          [[ -z "$FPS_IN" ]] && FPS_IN=24
          EXTRA_TOL=""
          if [[ -n "$TOL" ]]; then
            EXTRA_TOL="--tolerance-seconds $TOL"
          fi
          python scripts/generate_timelapse_last7days.py \
            --step-mins "$STEP" $EXTRA_TOL --fps "$FPS_IN" | tee generate7.log
          used=$(grep -m1 "^Used " generate7.log | awk '{print $2}' || echo "0")
          echo "frames_used=${used}" >> $GITHUB_OUTPUT

      - name: Create tag for release
        id: tag
        run: echo "tag=timelapse-7d-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Publish MP4 to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "Timelapse (Last 7 Days) — ${{ steps.tag.outputs.tag }}"
          files: timelapses/timelapse_last7days_*.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        if: always()
        run: |
          echo "## Last 7 Days Timelapse (Evenly Spaced)" >> "$GITHUB_STEP_SUMMARY"
          echo "- Frames used: ${{ steps.gen.outputs.frames_used }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Grid step (mins): ${{ github.event.inputs.step_mins || '5' }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Tolerance (sec): ${{ github.event.inputs.tolerance_seconds || 'step/2' }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- FPS: ${{ github.event.inputs.fps || '24' }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Output: attached to the newly created Release" >> "$GITHUB_STEP_SUMMARY"
